@echo off
echo Stopping Employee Leave Management System...
echo Terminating Java processes...
taskkill /F /IM java.exe 2>nul
echo Terminating Node processes...
taskkill /F /IM node.exe 2>nul
echo Shutting down MySQL Database...
call stop-db.bat
echo All systems stopped.
